### ISSUE TITLE
Publish a binary redistributable file

### ISSUE THREAD

**Issue by jjpaulo2** [ZorgeR/DroidFlasher#3]
Could you publish a `.jar` file from the project? This project looks good to me, and would be cool to share it with non developer friends or any people.

**Comment by ZorgeR** [comment]
You can find build version here - https://firmware.center/projects/DroidFlasher/build/r110/

**Comment by jjpaulo2** [comment]
@ZorgeR sorry for the delay to answer your comment. Thanks by share this link. 
I can add it into you readme.
